spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_exemplo_test?useTimezonetrue
    username: root
    password: jean1420
  jpa:
    hibernate.ddl-auto: update
    show-sql: false